name: Deploy to S3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v4
      #   with:
      #     version: 9

      # - name: Install dependencies and build
      #   run: |
      #     pnpm install
      #     pnpm run build

      - name: Check if AWS_ACCESS_KEY_ID is accessible
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          echo "$AWS_ACCESS_KEY_ID is accessible"
          echo "Github Token ${{secrets.GITHUB_TOKEN}}"
          echo "FOOBAR: ${{secrets.FOOBAR}}"
          echo "secrets: ${{secrets}}"
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "AWS_ACCESS_KEY_ID is not available"
            exit 1
          else
            echo "AWS_ACCESS_KEY_ID is available"
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          output-credentials: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync files to S3
        run: |
          aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
